#!/bin/bash

bld="bld"
game="SuperGame"

ls | sed 's/bld//;s/build//' | zip -r bld/$game.love -@

#win
cat $bld/stf/win/love.exe $bld/$game.love > $bld/win/$game.exe
cp $bld/stf/win/*.dll $bld/win/
cp $bld/stf/win/license.txt $bld/win/
#--

cp $bld/stf/mac/love.app $bld/mac/$game.app
cp $bld/$game.love $bld/mac/$game.app/Contents/Resources/$game.love
#-->

#mac
